### ISSUE TITLE
v1.1 bugs

### ISSUE THREAD

**Issue by ViWalls** [Cram-o-dev/cramorantedition#4]
I'm playing latest release on an Ez Flash Jr using original hardware.

- The second Blue encounter (left Viridian, before Victory Road hallway) creates a second blue NPC standing where he cames from. It will stay there until you refresh the map and even you can talk to him!
- The new wooden house in Viridian Forest has a Town map that marks the location of Indigo Plateau instead of Viridian Forest. If you leave the house, also Cramoran sprite will be located one tile above the door's threshold instead of waiting for the player to get pushed out.

I just started the adventure and I'm on Pewter City. I will report more stuff if I find it.

**Comment by Cram-o-dev** [comment]
Hi, thanks for letting me know, will look into those!
The second Blue encounter is strange; I've never seen that before in any of my playthroughs or testing.

**Comment by ViWalls** [comment]
For this reason I mentioned I'm playing on Ez Flash Jr, just in case it's an emulation problem. Said that rarely I encounter significant bugs due to emulation, I play a lot of romhacks with it.

Another couple of things to give a look:
- There are no fossil in Mt Moon, the path it's open and you can't interact with the tiles where Dome and Helix are located neither.
- Also Jessie & James are there before reaching the tile that activates the event when you're leaving Mt Moon, standing still. You can interact with them showing a blank text box. The event works as intended, but you must pass through them and are not hidden before triggering the event.

I used the latest patch in this repo on a good dump made by me of pret Yellow.

**Comment by Cram-o-dev** [comment]
It might be your emulator. I've never seen those issues happen nor have I seen anyone else encounter those issues.

**Comment by ViWalls** [comment]
Then I can confirm the romhack is not working properly on Ez Flash Jr. Is not unplayable, you can still progress with no problem but you will find weird things along the adventure and miss a couple of features (specially with the hidden stuff and NPCs).

It's kinda weird to me because until now the only flash cart related malfunctions were all graphic glitches, but not affecting gameplay, field items or NPCs.

Anyways nice and funny romhack, good job!

**Comment by Cram-o-dev** [comment]
Thank you! I have confirmed the minor quirks with Cramorant's sprite when you leave the new house in Viridian Forest, and the incorrect Town Map entries are present. I'm not sure what the deal is with Cramorant's sprite, but for the town maps, I forgot to include the new maps I made in data\maps\town_map_entries.asm. I have fixed this, so now all the new maps accurately show where you are, instead of at the Pokemon League.

**Comment by Cram-o-dev** [comment]
I've now managed to fix the Cramorant spawning into the wall of the viridian house when exiting it. It appears only in the doorway ,just like when leaving every other building. A minor consequence of this is that Cramorant now no longer spawns at the same time as you when you enter the forest, but it appears once you take a step.

**Comment by Cram-o-dev** [comment]
The project has now been updated to version 1.2. Closing this and opening a new issue for 1.2 where any bugs can be reported.
