### ISSUE TITLE
Better Walkthrough how to install and Building Cramorant Edition

### ISSUE THREAD

**Issue by youarereclaimer** [Cram-o-dev/cramorantedition#6]
I didn't have the easiest time following the installation/build instructions. Here is hopefully an easier guided walkthrough, enjoy!

Windows 10 using windows subsystem linux:

(Need to install/activate windows subsystem Linux first)

(run cmd prompt as admin)

wsl --install -d Debian

user: su
pass: xxxxxxxx

sudo apt-get update && apt-get upgrade

[set as default distribution]
wsl -s Debian

cd /mnt/c/Users/<user>/Desktop
( sets file path on desktop)

(install required files for build cramorant pokeyellow)

A.) sudo apt-get install make gcc git

B.) 
# Install package from the package manager
sudo apt-get install python3 build-essential bison libboost-dev libpng-dev flex texinfo pkg-config

C.)
sudo apt install wget
(need to install wget first)

D.) 
# Get and build sdcc
wget https://sourceforge.net/projects/sdcc/files/sdcc/4.2.0/sdcc-src-4.2.0.tar.bz2/download -O sdcc-src.tar.bz2
tar -xjvf sdcc-src.tar.bz2
cd sdcc-4.2.0
./configure --disable-pic14-port  --disable-pic16-port
make -j$(nproc)
sudo make install
cd ..

E.) 
# Get and build rgbds
wget https://github.com/gbdev/rgbds/releases/download/v0.6.0/rgbds-0.6.0.tar.gz -O rgbds-src.tar.gz
tar -xzvf rgbds-src.tar.gz
cd rgbds
make
sudo make install
cd ..

(download and build pokeyellow - cramorant edition)
git clone https://github.com/Cram-o-dev/cramorantedition.git

(cd /mnt/c/Users/localacc/Desktop)

cd cramorantedition

make

__________________________________________________

download mGBA emulator, and open the pokeyellow.gbc rom file inside cramorantedition folder 

then play!

**Comment by Cram-o-dev** [comment]
Thanks, a nice guide on building it for those who may need it.
