### ISSUE TITLE
.md Files for Hidden Items, Pokemon Locations/Level-Up Moves/Information, and Move List

### ISSUE THREAD

**Issue by usernamewyatt** [Cram-o-dev/cramorantedition#7]
Hello, I didn't know if these could be of use. I absolutely love this game so I migrated the information in the spreadsheet to .md files so I could build myself a little Obsidian wiki. I'm sorry if this is the wrong place, but thank you so much for a game of my favorite Pokemon.

[Pokemon Cramorant Information.zip](https://github.com/Cram-o-dev/cramorantedition/files/14145767/Pokemon.Cramorant.Information.zip)

**Comment by Cram-o-dev** [comment]
You're welcome! That is very cool, and I'm glad you enjoyed my rom hack.
